# Site settings
author: Jamal Rjoul
title: CLI PROJECT - ACTORINFO 
header-img: img/home-bg.png
email: jamensky1991@gmail.com
copyright_name: Jamal Rjoul
description: > # this means to ignore newlines until "baseurl:"
  Learn more about your favorite actor! 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  jamensky

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
